name: CI

on:
  pull_request:
  release:
    types:
      - published

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: npm install
    - name: Release prebuilt artifacts
      if: github.event_name == 'release' && github.event.action == 'published'
      run: npx prebuild -t 9.0.0 -t 10.0.0 -t 11.0.0 -t 12.0.0 -r electron -u ${{ secrets.PUBLISH_TOKEN }}
