name: CI

on:
  pull_request:
  release:
    types:
      - published

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install
      - run: npm run test
      - name: Release prebuilt artifacts
        if: github.event_name == 'release' && github.event.action == 'published'
        run: npx prebuild -t 18.0.0 -t 19.0.0 -t 20.0.0 -t 21.0.0 -r electron -u ${{ secrets.PUBLISH_TOKEN }}
